### ISSUE TITLE
SoapClient::__call — Calls a SOAP function (deprecated)

### ISSUE THREAD

**Issue by eturerer** [meabed/php-parallel-soap#74]
https://github.com/meabed/php-parallel-soap/blob/3ee862679f4af8fccd5152fc7196a8032688bca2/src/ParallelSoapClient.php#L345

and

ParallelSoapClient::getResponseResult(): Return value must be of type string, stdClass returned in parallel_soap_client.php on line 546

    public function getResponseResult(string $method, $args): string {

        $resFn = $this->resFn;
        return $resFn($method, $res);

**Comment by meabed** [comment]
Thank you @eturerer I am releasing and update this week to fix this.

**Comment by Axent96** [comment]
@meabed is it planed for a fix?

**Comment by crmb** [comment]
I have this error with PHP 8.2
I imagine this is related :+1: 

Deprecated: Return type of Soap\ParallelSoapClient::__call($method, $args) should either be compatible with SoapClient::__call(string $name, array $args): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by meabed** [comment]
Thank you, I will address this and fix shortly.
