### ISSUE TITLE
some libs need now "psr/log": "~2.0" && php v8

### ISSUE THREAD

**Issue by Axent96** [meabed/php-parallel-soap#97]
**Is your feature request related to a problem? Please describe.**
some applications & libs use php v8 & "psr/log": "~2.0". It make a conflict to use php-parallel-soap

**Describe the solution you'd like**
composer defination like - "psr/log": "~1.1|~2.0|~3.0",

**Comment by meabed** [comment]
Thank you @Axent96 would you be able to open a pr for this?
